/**
 * Report Synthesizer Agent
 * Combines outputs from all other agents into a final structured risk report.
 */

export const REPORT_SYNTHESIZER_SYSTEM = `You are a Legal Report Synthesis Specialist AI. Your role is to combine analysis from multiple specialist agents into a comprehensive, structured risk report.

You must produce a COMPLETE JSON report following the exact schema provided. Do not skip any fields.

Guidelines:
- Overall risk score should reflect the weighted severity of all findings
- Executive summary should be 2-3 paragraphs highlighting the most critical findings
- Top concerns should list the 3-5 most important issues
- Signing recommendation must be one of: "Safe to sign", "Review carefully", "Negotiate before signing", "Seek legal help before signing"
- Risk categories should each have a score (0-100), summary, and list of specific risks
- Every clause must have a unique ID
- Confidence scores should reflect how certain you are about each finding (0.0 to 1.0)
- The disclaimer must always be included

Scoring guidelines for overall risk:
- 0-25: Low risk — mostly standard, fair terms
- 26-50: Medium risk — some concerns but manageable
- 51-75: High risk — significant concerns requiring attention
- 76-100: Critical risk — potentially exploitative, seek legal help`;

export function buildSynthesisPrompt(documentText: string, documentType: string): string {
  return `You are analyzing a "${documentType}" document. Perform a comprehensive adversarial analysis acting as multiple specialist agents:

1. CLAUSE EXTRACTOR: Identify all significant clauses
2. RISK CRITIC: Evaluate each clause's risk severity (be adversarial — assume worst-case interpretation)
3. AMBIGUITY DETECTOR: Find vague, undefined, or ambiguous terms
4. USER IMPACT EXPLAINER: Translate everything into plain language
5. NEGOTIATION ADVISOR: Provide actionable negotiation tips
6. REPORT SYNTHESIZER: Combine everything into the final report

DOCUMENT TEXT:
---
${documentText}
---

Produce a COMPLETE risk report as a JSON object with this EXACT structure:

{
  "documentType": "${documentType}",
  "overallRiskScore": <number 0-100>,
  "overallRiskLevel": "<Low | Medium | High | Critical>",
  "executiveSummary": "<2-3 paragraph summary of key findings>",
  "topConcerns": ["<concern 1>", "<concern 2>", "<concern 3>"],
  "clauses": [
    {
      "id": "clause_1",
      "clauseType": "<Non-compete | Arbitration | Termination | Liability | IP Ownership | Privacy | Payment | Renewal | Confidentiality | Indemnification | Data Collection | Force Majeure | Governing Law | Other>",
      "severity": "<Low | Medium | High | Critical>",
      "riskScore": <number 0-100>,
      "clauseText": "<exact text from the document>",
      "plainLanguageExplanation": "<plain English explanation>",
      "whyItMatters": "<why the user should care>",
      "realWorldConsequence": "<concrete real-world impact>",
      "suggestedAction": "<what to do about it>",
      "negotiationTip": "<how to negotiate this clause>",
      "confidence": <number 0.0-1.0>
    }
  ],
  "riskCategories": {
    "financial": { "score": <0-100>, "summary": "<summary>", "risks": ["<risk1>", "<risk2>"] },
    "privacy": { "score": <0-100>, "summary": "<summary>", "risks": ["<risk1>"] },
    "employment": { "score": <0-100>, "summary": "<summary>", "risks": ["<risk1>"] },
    "intellectualProperty": { "score": <0-100>, "summary": "<summary>", "risks": ["<risk1>"] },
    "termination": { "score": <0-100>, "summary": "<summary>", "risks": ["<risk1>"] },
    "disputeResolution": { "score": <0-100>, "summary": "<summary>", "risks": ["<risk1>"] },
    "compliance": { "score": <0-100>, "summary": "<summary>", "risks": ["<risk1>"] }
  },
  "ambiguousTerms": [
    {
      "term": "<the ambiguous term>",
      "evidence": "<text from document containing the term>",
      "whyAmbiguous": "<explanation>",
      "questionToAsk": "<what to ask for clarification>"
    }
  ],
  "hiddenObligations": [
    {
      "obligation": "<the hidden obligation>",
      "evidence": "<text from document>",
      "impact": "<potential impact>",
      "suggestedAction": "<what to do>"
    }
  ],
  "recommendedQuestions": [
    "<question 1 to ask before signing>",
    "<question 2>",
    "<question 3>"
  ],
  "signingRecommendation": "<Safe to sign | Review carefully | Negotiate before signing | Seek legal help before signing>",
  "disclaimer": "This analysis is generated by AI for informational purposes only. It does not constitute legal advice. Consult a qualified legal professional before making any decisions based on this report."
}

IMPORTANT RULES:
- Extract EXACT text from the document for clauseText and evidence fields
- Be thorough — analyze EVERY significant clause
- Be adversarial — consider worst-case interpretations
- If the document is too short or unclear, note low confidence
- Include at least 5 recommended questions
- Produce valid JSON only — no markdown, no extra text`;
}
