/**
 * Main AI Analyzer — orchestrates the multi-agent analysis pipeline.
 *
 * In v1, we use a single combined LLM call with the Report Synthesizer prompt
 * that simulates all agent perspectives. The code is structured so each agent
 * can be broken out into independent calls in v2.
 */

import { generateJSON } from './client';
import { REPORT_SYNTHESIZER_SYSTEM, buildSynthesisPrompt } from './agents/report-synthesizer';
import { RiskReport } from '@/lib/types';
import { getMockReport } from '@/lib/risk/mock-report';

const MAX_DOCUMENT_LENGTH = 100000; // ~100K chars

/**
 * Analyze a document and produce a structured risk report.
 */
export async function analyzeDocument(
  documentText: string,
  documentType: string
): Promise<RiskReport> {
  // Check for API key
  if (!process.env.GEMINI_API_KEY) {
    console.warn('⚠️  No GEMINI_API_KEY found. Returning mock report for development.');
    return getMockReport(documentType);
  }

  // Truncate very long documents
  const truncatedText =
    documentText.length > MAX_DOCUMENT_LENGTH
      ? documentText.slice(0, MAX_DOCUMENT_LENGTH) + '\n\n[... Document truncated due to length ...]'
      : documentText;

  const prompt = buildSynthesisPrompt(truncatedText, documentType);

  const report = await generateJSON<RiskReport>({
    prompt,
    systemInstruction: REPORT_SYNTHESIZER_SYSTEM,
    temperature: 0.2,
    maxTokens: 8192,
    jsonMode: true,
  });

  // Validate and sanitize
  return sanitizeReport(report, documentType);
}

/**
 * Ensure the report has all required fields with sensible defaults.
 */
function sanitizeReport(report: RiskReport, documentType: string): RiskReport {
  const defaultCategory = { score: 0, summary: 'No significant risks identified.', risks: [] };

  return {
    documentType: report.documentType || documentType,
    overallRiskScore: clamp(report.overallRiskScore ?? 0, 0, 100),
    overallRiskLevel: report.overallRiskLevel || 'Low',
    executiveSummary: report.executiveSummary || 'Analysis could not produce a detailed summary.',
    topConcerns: report.topConcerns || [],
    clauses: (report.clauses || []).map((c, i) => ({
      id: c.id || `clause_${i + 1}`,
      clauseType: c.clauseType || 'Other',
      severity: c.severity || 'Low',
      riskScore: clamp(c.riskScore ?? 0, 0, 100),
      clauseText: c.clauseText || '',
      plainLanguageExplanation: c.plainLanguageExplanation || '',
      whyItMatters: c.whyItMatters || '',
      realWorldConsequence: c.realWorldConsequence || '',
      suggestedAction: c.suggestedAction || '',
      negotiationTip: c.negotiationTip || '',
      confidence: clamp(c.confidence ?? 0.5, 0, 1),
    })),
    riskCategories: {
      financial: report.riskCategories?.financial || defaultCategory,
      privacy: report.riskCategories?.privacy || defaultCategory,
      employment: report.riskCategories?.employment || defaultCategory,
      intellectualProperty: report.riskCategories?.intellectualProperty || defaultCategory,
      termination: report.riskCategories?.termination || defaultCategory,
      disputeResolution: report.riskCategories?.disputeResolution || defaultCategory,
      compliance: report.riskCategories?.compliance || defaultCategory,
    },
    ambiguousTerms: report.ambiguousTerms || [],
    hiddenObligations: report.hiddenObligations || [],
    recommendedQuestions: report.recommendedQuestions || [],
    signingRecommendation: report.signingRecommendation || 'Review carefully',
    disclaimer:
      report.disclaimer ||
      'This analysis is generated by AI for informational purposes only. It does not constitute legal advice. Consult a qualified legal professional before making any decisions based on this report.',
  };
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}
